### ISSUE TITLE
AMD Ryzen 9000 iGPU

### ISSUE THREAD

**Issue by jzetterman** [HikariKnight/quickpassthrough#30]
I've got a 9900X. It detects AMD Granite Ridge, but when selecting use this GPU there's a runtime error causing the script to panic and exit. My second GPU is a Radeon RX 6700XT.

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/HikariKnight/quickpassthrough/internal/pages.genVBIOS_dumper(0xc0003cb1a0)
	/home/john/Downloads/quickpassthrough/internal/pages/03_vbios_extract.go:30 +0x65f
github.com/HikariKnight/quickpassthrough/internal/pages.viewGPU(0xc0003cb1a0, {0x0?, 0x0, 0x2?})
	/home/john/Downloads/quickpassthrough/internal/pages/02_select_gpu.go:108 +0x4b5
github.com/HikariKnight/quickpassthrough/internal/pages.SelectGPU(0xc0003cb1a0)
	/home/john/Downloads/quickpassthrough/internal/pages/02_select_gpu.go:37 +0x105
github.com/HikariKnight/quickpassthrough/internal/pages.Welcome()
	/home/john/Downloads/quickpassthrough/internal/pages/01_welcome.go:48 +0x245
github.com/HikariKnight/quickpassthrough/internal.Tui()
	/home/john/Downloads/quickpassthrough/internal/ui_main.go:24 +0xc5
main.main()
	/home/john/Downloads/quickpassthrough/cmd/main.go:23 +0xa5

**Comment by HikariKnight** [comment]
can you please provide me with the logfile, that way i can see everything the program sees and what you select :)

**Comment by HikariKnight** [comment]
@jzetterman can you please provide me with the logfile, that way i can see everything the program sees and what you select :slightly_smiling_face:

**Comment by jzetterman** [comment]
Here it is. Another thing to note, I recently upgraded my PC, but did not reinstall the OS so I had originally run it before with the 6700XT and a GTX 1050 where the 1050 was the passthrough GPU. For some reason the log file doesn't want to attach, so I've pasted it in below. 

sudo cat quickpassthrough_debug.log
[sudo] password for john:
2024/11/17 11:58:51
Welcome to Quickpassthrough 4f51fd5!

2024/11/17 11:58:53
/etc/modprobe.d found on the system
Creating config/etc/modprobe.d

2024/11/17 11:58:53
/etc/default found on the system
Creating config/etc/default

2024/11/17 11:58:53
/etc/mkinitcpio.conf found on the system
Creating config/etc/mkinitcpio.conf

2024/11/17 11:58:53
/etc/default/grub found on the system
Creating config/etc/default/grub

2024/11/17 11:58:53
Executing: utils/ls-iommu -g -F vendor:,prod_name,optional_revision:,device_id

2024/11/17 11:58:53
ls-iommu query returned
IOMMU Group  14: Advanced Micro Devices, Inc. [AMD/ATI]: Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] (rev c1): [1002:73df]
IOMMU Group  28: Advanced Micro Devices, Inc. [AMD/ATI]: Granite Ridge [Radeon Graphics] (rev c2): [1002:13c0]

2024/11/17 11:58:54
Executing: utils/ls-iommu -g -r -i 28 -F vendor:,prod_name,optional_revision:,device_id

2024/11/17 11:58:54
ls-iommu query returned
IOMMU Group  28: Advanced Micro Devices, Inc. [AMD/ATI]: Granite Ridge [Radeon Graphics] (rev c2): [1002:13c0]

2024/11/17 11:58:56
Executing: utils/ls-iommu -g -r -i 28 --id

2024/11/17 11:58:56
ls-iommu query returned
1002:13c0

2024/11/17 11:58:56
Executing: utils/ls-iommu -g -i 28 --rom

2024/11/17 11:58:56
ls-iommu query returned

**Comment by HikariKnight** [comment]
@jzetterman what is the output given by `utils/ls-iommu -g -i 28 --rom` run from the same directory as the quickpassthrough binary?
want to rule out the issue being in the ls-iommu project

**Comment by jzetterman** [comment]
That returns no output and no error. Just nothing.

Thank you,

John Zetterman
________________________________

**Comment by jedrw** [comment]
I just put up a  PR (#31) that I think should fix this. However I think it's worth mentioning that this wont guarantee a working passthrough configuration. In my experience with playing with passing through various iGPUs over the years it's pretty hit and miss. At the very least my PR should enable users to try using quickpassthrough for initial configuration of an iGPU passthrough.

**Comment by jzetterman** [comment]
I moved to passing through my dGPU for now, but I'll be happy to test this once it's been approved and merged.

**Comment by HikariKnight** [comment]
Merged this now thank you @jedrw

**Comment by HikariKnight** [comment]
@jzetterman its merged (again) if you want to test it
